name: Get Fit With Debbie
favicon: null
layout_spectrum: 0.16923
typography_spectrum: 0.4261994392145425
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cdc6be'
    - '#a3521d'
    - '#06080c'
    - '#0c5d9b'
  brandStrength: 0.010838315589353442
  lightness: 0.08377687190659344
  saturation: 0.7459807549603283
  rhythmicContrast: 0.16386109520681202
purpose: []
